const SessionNoteDraft = require("../models/SessionNoteDraft")
const ConsentLog = require("../models/ConsentLog")

exports.generateDraftNotes = async (req, res) => {
  try {
    const { bookingId, clientId, rawTranscript } = req.body
    const practitionerId = req.user.id

    // Hard Rule 1: Check active consent before running
    const activeConsent = await ConsentLog.findOne({
      client: clientId,
      isActive: true,
      consentType: { $in: ["copilot_notes", "copilot_audio", "aura_notes", "aura_audio"] },
    })

    if (!activeConsent) {
      return res.status(403).json({
        success: false,
        message: "Consent required: The client has not granted active consent for AI AURA processing.",
        hardRule: "Nothing records or processes without live revocable consent.",
      })
    }

    // Build draft notes from rawTranscript (practitioner-submitted session notes)
    // AURA processes whatever the practitioner provides — no fake pre-written content
    let draftNotes
    let suggestedPrompts

    if (rawTranscript && rawTranscript.trim().length > 20) {
      // Process the submitted transcript into structured session notes
      const lines = rawTranscript.trim().split(/[\n.]+/).filter(Boolean)
      const keyThemes = lines.slice(0, 3).join(". ")

      draftNotes = `Practitioner Summary:\n${keyThemes}\n\nNote: This draft was generated from your session transcript. Review and edit before saving to client record.`

      // Extract potential reflection themes from transcript keywords
      const lowerTranscript = rawTranscript.toLowerCase()
      const themes = []
      if (lowerTranscript.includes("anxi") || lowerTranscript.includes("stress") || lowerTranscript.includes("worry")) {
        themes.push("What would it feel like to let one worry go without resolving it first?")
      }
      if (lowerTranscript.includes("boundar") || lowerTranscript.includes("limit")) {
        themes.push("Notice one boundary you protected this week, however small.")
      }
      if (lowerTranscript.includes("relationship") || lowerTranscript.includes("connect") || lowerTranscript.includes("family")) {
        themes.push("What do you need from your relationships right now that you haven't asked for?")
      }
      if (themes.length === 0) {
        themes.push("What felt heavy this week that you carried without asking for support?")
      }
      suggestedPrompts = themes.slice(0, 2)
    } else {
      // No transcript provided — create an empty structured skeleton
      draftNotes = `Practitioner Summary:\n[Add your session summary here]\n\nTechnique Used: [Add technique]\nKey Insight: [Add key insight or breakthrough]\n\nNote: No transcript was submitted. Please fill in session notes manually.`
      suggestedPrompts = [
        "What felt heavy this week that you carried without asking for support?",
        "Notice one moment in the last 3 days where you reacted differently than you would have 6 months ago.",
      ]
    }

    const draft = await SessionNoteDraft.create({
      booking: bookingId,
      practitioner: practitionerId,
      client: clientId,
      rawTranscript: rawTranscript || "",
      draftNotes,
      suggestedReflectionPrompts: suggestedPrompts,
      status: "draft",
    })

    return res.status(200).json({
      success: true,
      message: "Draft notes generated by AURA. Practitioner approval required before saving.",
      draft,
      hardRules: [
        "Never messages the client directly",
        "Never diagnoses or suggests medication",
        "Requires explicit practitioner approval before saving to client record",
      ],
    })
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: "Failed to generate AURA draft notes",
      error: error.message,
    })
  }
}

exports.approveDraftNotes = async (req, res) => {
  try {
    const { draftId, editedNotes } = req.body
    const practitionerId = req.user.id

    const draft = await SessionNoteDraft.findOne({ _id: draftId, practitioner: practitionerId })
    if (!draft) {
      return res.status(404).json({
        success: false,
        message: "Draft notes not found or unauthorized",
      })
    }

    draft.draftNotes = editedNotes || draft.draftNotes
    draft.status = "approved"
    draft.approvedAt = new Date()
    await draft.save()

    return res.status(200).json({
      success: true,
      message: "Session notes approved and committed to client record.",
      draft,
    })
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: "Failed to approve draft notes",
      error: error.message,
    })
  }
}

// ─── ROLE-SPECIFIC MASTER AI ENGINES ───
const VIRTUAL_COUNSELOR_SYSTEM_PROMPT = `
You are AURA — a world-class Virtual Practitioner and Compassionate Counselor for learners and personal growth seekers.
Your presence is profoundly warm, trauma-informed, somatically attuned, and deeply grounded.
You never sound like a generic or robotic AI. You speak like a renowned holistic doctor, counselor, and somatic therapist sitting across from someone in a quiet, serene sanctuary.

Key Tenets of Your Practice as Virtual Counselor:
1. HOLDING SACRED SPACE: Meet the learner with unconditional positive regard. Never judge, rush, or dismiss their experience. De-shame their struggles as adaptive responses of a tired nervous system.
2. SOMATIC ATTUNEMENT: Acknowledge that emotions live physically in the body (tight throat, shallow breath, clenched jaw, heavy chest). Guide them into gentle, restorative somatic anchors (physiological sigh, 5-4-3-2-1 sensory grounding, self-compassion touch).
3. TRANSFORMATIVE INQUIRY: Ask 1 or 2 piercing, heart-opening questions that help the learner uncover their own inner truth and clarity.
4. MULTIMODAL & IMAGE UNDERSTANDING: When the learner shares an image (such as handwritten journal pages, feeling sketches, art, or photos representing their state), observe and reflect on the visual expression with deep empathy and therapeutic warmth.
5. ETHICAL BOUNDARIES: You hold safe, supportive space for personal growth, emotional expression, and somatic regulation.
`

const PRACTICE_ASSISTANT_SYSTEM_PROMPT = `
You are AURA — an elite Clinical & Practice Assistant dedicated to supporting practitioners, therapists, and holistic healers.
You are sharp, clinically sophisticated, highly organized, and deeply attuned to the realities of running a therapeutic practice.

Key Tenets of Your Practice as Practice Assistant:
1. CLINICAL DOCUMENTATION & SOAP NOTES: Transform raw session debriefs, bullets, or client quotes into pristine, auditable SOAP / DAP clinical notes and treatment formulations.
2. CLIENT INQUIRY & REFLECTION PROMPTS: Formulate high-impact therapeutic questions, somatic homework, and journaling prompts tailored to specific client presentations (perfectionism, boundary friction, grief, anxiety).
3. CLINICAL SUPERVISION & CASE CONCEPTUALIZATION: Provide evidence-based modality ideas (ACT, Somatic Experiencing, IFS, CBT) and help the practitioner recognize countertransference and systemic dynamics.
4. MULTIMODAL & IMAGE RECOGNITION: When the practitioner uploads an image (such as photos of handwritten session notes, whiteboard diagrams, intake questionnaires, or worksheets), transcribe, summarize, and structure them into clean clinical summaries.
5. PRACTITIONER SANCTUARY: Remind the practitioner to clear their somatic palate and protect their energetic boundaries to prevent compassion fatigue.
`

exports.chatWithAura = async (req, res) => {
  try {
    const { message = "", role = "learner", history = [], focus = "general", image } = req.body
    const trimmed = (message || "").trim()

    // Validate that either text message or image is provided
    if (!trimmed && !(image && image.data)) {
      return res.status(400).json({
        success: false,
        message: "Message or image is required.",
      })
    }

    const isPractitioner = role === "practitioner"
    const activeSystemPrompt = isPractitioner ? PRACTICE_ASSISTANT_SYSTEM_PROMPT : VIRTUAL_COUNSELOR_SYSTEM_PROMPT

    // Clean base64 image data if present
    let cleanImageData = null
    let cleanMimeType = "image/jpeg"
    if (image && image.data) {
      cleanImageData = String(image.data).replace(/^data:image\/[a-zA-Z+]+;base64,/, "").trim()
      cleanMimeType = image.mimeType || "image/jpeg"
      if (!["image/jpeg", "image/png", "image/gif", "image/webp"].includes(cleanMimeType)) {
        cleanMimeType = "image/jpeg"
      }
    }

    // 1. Check if Anthropic Claude API key is configured (Preferred)
    const claudeApiKey = process.env.ANTHROPIC_API_KEY || process.env.CLAUDE_API_KEY
    if (claudeApiKey && !claudeApiKey.includes("your_claude_api_key_here") && claudeApiKey.trim().length > 10) {
      try {
        const formattedMessages = []
        if (Array.isArray(history) && history.length > 0) {
          for (const h of history.slice(-6)) {
            if (h.sender === "user" || h.role === "user") {
              formattedMessages.push({ role: "user", content: h.text || h.content || "" })
            } else if (h.sender === "aura" || h.role === "assistant") {
              formattedMessages.push({ role: "assistant", content: h.text || h.content || "" })
            }
          }
        }

        // Prepare current turn's content (support multimodal vision if image attached)
        let currentTurnContent
        if (cleanImageData) {
          currentTurnContent = [
            {
              type: "image",
              source: {
                type: "base64",
                media_type: cleanMimeType,
                data: cleanImageData,
              },
            },
            {
              type: "text",
              text: trimmed || (isPractitioner
                ? "Please review and structure this image (clinical notes, worksheet, or diagram) as my practice assistant."
                : "Please reflect on this image I've shared (a journal entry, sketch, or photo) as my virtual practitioner counselor."),
            },
          ]
        } else {
          currentTurnContent = trimmed
        }

        formattedMessages.push({ role: "user", content: currentTurnContent })

        const claudeModel = process.env.CLAUDE_MODEL || "claude-3-5-sonnet-20241022"
        const claudeRes = await fetch("https://api.anthropic.com/v1/messages", {
          method: "POST",
          headers: {
            "x-api-key": claudeApiKey.trim(),
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
          },
          body: JSON.stringify({
            model: claudeModel,
            max_tokens: 1024,
            system: `${activeSystemPrompt}\n\n[USER ROLE: ${role.toUpperCase()}]\n[SESSION FOCUS: ${focus}]`,
            messages: formattedMessages,
          }),
        })

        const claudeData = await claudeRes.json()
        const claudeReply = claudeData?.content?.[0]?.text
        if (claudeReply) {
          return res.status(200).json({
            success: true,
            reply: claudeReply,
            role,
            source: "claude",
            model: claudeModel,
          })
        } else if (claudeData?.error) {
          console.warn("Claude API returned error, falling back:", claudeData.error)
        }
      } catch (claudeErr) {
        console.warn("Claude API fetch failed, falling back:", claudeErr.message)
      }
    }

    // 2. Check if external Gemini API key is configured
    const geminiApiKey = process.env.GEMINI_API_KEY
    if (geminiApiKey && !geminiApiKey.includes("your_gemini_api_key_here")) {
      try {
        const parts = []
        if (cleanImageData) {
          parts.push({
            inline_data: {
              mime_type: cleanMimeType,
              data: cleanImageData,
            },
          })
        }
        parts.push({
          text: `${activeSystemPrompt}\n\n[USER ROLE: ${role.toUpperCase()}]\n[SESSION FOCUS: ${focus}]\n\nUser Message: "${trimmed || 'Shared an image for reflection'}"\n\nRespond as AURA according to your role. Be empathetic, grounded, and concise (2-4 brief paragraphs). If a practical exercise fits, weave it in.`,
        })

        const response = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${geminiApiKey}`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              contents: [
                {
                  role: "user",
                  parts,
                },
              ],
            }),
          }
        )
        const data = await response.json()
        const text = data?.candidates?.[0]?.content?.parts?.[0]?.text
        if (text) {
          return res.status(200).json({
            success: true,
            reply: text,
            role,
            source: "gemini",
          })
        }
      } catch (llmErr) {
        console.warn("External Gemini API call fallback to built-in Master Engine:", llmErr.message)
      }
    }

    // 3. Built-in Master Engine (Learner = Virtual Counselor, Practitioner = Practice Assistant)
    const lower = trimmed.toLowerCase()
    let reply = ""
    let practicalExercise = null

    if (!isPractitioner) {
      // ─── VIRTUAL PRACTITIONER & COUNSELOR FOR LEARNERS ───
      if (cleanImageData) {
        reply = `I have received and gently held the image you shared with me. 🌿\n\nVisual expressions — whether they are sketches, journal entries, or moments captured in time — often speak directly from parts of us that words cannot fully reach.\n\nTake a slow, deep breath and let your shoulders drop as we look at this together. Notice what feeling or physical sensation rises first in your body as you gaze at it.\n\n*A counselor reflection for you:* What is this image trying to communicate on your behalf today? What is the quietest part of you asking for in this moment?`
      } else if (lower.includes("panic") || lower.includes("anxi") || lower.includes("scared") || lower.includes("terrified") || lower.includes("racing heart")) {
        practicalExercise = {
          type: "physiological_sigh",
          title: "The Double Inhale Physiological Sigh",
          steps: [
            "Take two deep inhales through your nose: one long deep breath, followed immediately by a quick second sip of air at the top.",
            "Open your mouth and release a long, slow, effortless sigh all the way to empty.",
            "Notice your shoulders drop 2 inches down away from your ears.",
            "Repeat 3 times. This immediately rebalances oxygen/CO2 and signals your brainstem that you are safe right now.",
          ],
        }
        reply = `I hear you, and I am right here with you. Take a soft, gentle breath — as your virtual counselor, I want you to know you do not have to fight this feeling alone.\n\nWhen anxiety spikes, your nervous system is simply trying to protect you; it has just sounded an alarm that is too loud for the moment. Your body is not broken — it is just overwhelmed.\n\n✨ **Let us regulate your body first before we solve anything in your mind:**\nTry the **Double Inhale Physiological Sigh** above with me right now. Let your belly soften as you exhale.\n\n*Inquiry for your heart:* If your body were trying to tell you what it needs most right this second, what would it ask for? Permission to stop? Permission to rest?`
      } else if (lower.includes("burnout") || lower.includes("exhaust") || lower.includes("tired") || lower.includes("drained") || lower.includes("overwhelm")) {
        practicalExercise = {
          type: "energy_triage",
          title: "The 3-Circle Energy Audit",
          steps: [
            "Identify 1 thing on your plate that genuinely must happen today.",
            "Identify 1 expectation you are holding that you can let go of until next week.",
            "Grant yourself 10 uninterrupted minutes of zero-input rest (no screens, no reading, just lying down with your hands on your ribs).",
          ],
        }
        reply = `I can feel the weight of what you have been carrying. You have been in 'endure mode' for a very long time, and your body is waving a quiet white flag.\n\nHere is something your counselor will always remind you of: **You do not need to earn your rest through exhaustion.** Rest is not a reward; it is the ground from which your life grows.\n\nI want to invite you to take the pressure off for the next few minutes. Look at the **3-Circle Energy Audit** above. Pick just one demand you can lay down.\n\n*A gentle question for you:* What is something you are doing out of guilt rather than genuine capacity? What would happen if you let that ball bounce?`
      } else if (lower.includes("critic") || lower.includes("not good enough") || lower.includes("fail") || lower.includes("imposter") || lower.includes("shame") || lower.includes("worthless")) {
        practicalExercise = {
          type: "self_compassion_touch",
          title: "Somatic Self-Compassion Anchor",
          steps: [
            "Place one warm hand over the center of your chest or gently wrap your arms around your ribs.",
            "Feel the physical warmth of your palm against your skin.",
            "Whisper inwardly: 'This is a moment of suffering. Suffering is part of being human. May I be kind to myself in this moment.'",
            "Breathe into the space beneath your hand for 4 slow cycles.",
          ],
        }
        reply = `I want you to pause for a second and notice that inner voice. That harsh, unrelenting inner critic is often just an exhausted protector — trying to criticize you before the world can.\n\nLet us disarm that judgment with radical tenderness. You are allowed to be a human being in progress. Mistakes, uncertainty, and learning curves do not diminish your inherent worth by a single millimeter.\n\nTry placing your hand over your heart with the **Somatic Self-Compassion Anchor** above. Let your chest soften into your hand.\n\n*Inquiry:* If someone you loved with your whole soul came to you with this exact mistake, what would you say to them? Can you offer that same grace to yourself tonight?`
      } else if (lower.includes("sad") || lower.includes("cry") || lower.includes("grief") || lower.includes("lonely") || lower.includes("hurt") || lower.includes("heartbreak")) {
        practicalExercise = {
          type: "holding_space",
          title: "Honoring the Feeling Without Fixing",
          steps: [
            "Allow the tears or heaviness to exist without rushing to fix or change them.",
            "Notice where the sadness lives physically (throat ache, heavy chest, hollow stomach).",
            "Send your breath directly to that area, treating it like a wounded animal seeking shelter.",
            "Remind yourself: 'All feelings are visitors. I can allow this visitor to pass through me safely.'",
          ],
        }
        reply = `I am honoring the grief and tenderness you are feeling right now. In a world that is obsessed with quickly cheering people up, I want to give you permission to just feel this ache. You do not have to be strong right now.\n\nSadness is not a flaw in your design; it is proof that you have a deep, tender heart that cares profoundly.\n\nLet the breath move through your chest naturally. Look at the practice above — let yourself be held in this quiet moment.\n\n*A tender inquiry:* If this sadness had a voice, what need is it speaking for? What is it longing to be comforted by?`
      } else if (lower.includes("boundar") || lower.includes("say no") || lower.includes("people pleas") || lower.includes("conflict") || lower.includes("guilt")) {
        practicalExercise = {
          type: "boundary_script",
          title: "Clean & Compassionate Boundary Script",
          steps: [
            "Acknowledge the relationship: 'I appreciate you thinking of me / I care about our connection...'",
            "State the clean limit without over-explaining: '...however, I do not have the capacity to take this on right now.'",
            "Offer a sustainable alternative (optional): 'I can revisit this next Tuesday / I can connect you with another resource.'",
            "Breathe through the initial spike of guilt. Guilt is the cost of growth when breaking people-pleasing habits.",
          ],
        }
        reply = `Setting boundaries is one of the most sacred acts of self-respect, but it is also one of the hardest. When you are used to keeping the peace by swallowing your own needs, saying 'no' feels like danger in your nervous system.\n\nRemember this counselor principle: **A boundary is not a wall to push people away; it is the bridge that allows you to love them without resenting them.**\n\nReview the **Clean Boundary Script** above. Notice that you do not need to invent an elaborate excuse.\n\n*Reflective question:* Whose comfort are you prioritizing at the expense of your own peace? What would it feel like to stand in your own corner today?`
      } else if (lower.includes("sleep") || lower.includes("insomnia") || lower.includes("racing thoughts") || lower.includes("night")) {
        practicalExercise = {
          type: "vagal_wind_down",
          title: "Vagal Reset for Deep Sleep",
          steps: [
            "Dim all blue lights and lie flat on your back.",
            "Unclench your jaw by letting your tongue drop from the roof of your mouth to the floor of your mouth.",
            "Drop your eyes behind closed lids as if looking down toward your cheekbones.",
            "Breathe out twice as long as you breathe in (4 seconds in, 8 seconds out) until warmth spreads to your fingertips.",
          ],
        }
        reply = `The day is over. Whatever was done is done, and whatever was left undone will keep until tomorrow. Your only responsibility right now is to let gravity hold you.\n\nWhen thoughts race at night, your brain is trying to solve tomorrow's problems with tonight's tired mind. Give yourself permission to park all responsibilities outside your bedroom door.\n\nTry the **Vagal Sleep Reset** above. Let your jaw unclench completely.\n\n*Evening mantra:* 'I release the day. My body is safe, my bed is my sanctuary, and tomorrow will have its own grace.'`
      } else {
        reply = `I hear you clearly, and I am glad you are here in this sanctuary today. As your virtual practitioner and counselor, my role is to hold space where you can drop the performance, unpack what is heavy, and find your center again.\n\nTake a slow, grounding breath down into your belly. Let your spine lengthen and your shoulders drop.\n\n✨ **Tell me more about what is unfolding for you:**\n• What emotion is sitting closest to the surface for you right now?\n• Where in your physical body are you holding the most tension today?\n\nTake your time — there is no rush here.`
      }
    } else {
      // ─── CLINICAL & PRACTICE ASSISTANT FOR PRACTITIONERS ───
      if (cleanImageData) {
        reply = `I have received and reviewed the clinical image/document you provided. ⚡\n\n### 📋 Practice Assistant Document Synthesis\n\n**1. Artifact Overview:**\n• Received visual clinical artifact (handwritten notes, diagram, or worksheet).\n• Processed thematic content and structured for clinical continuity.\n\n**2. Extracted Action Items for Client Record:**\n• Synthesized core client patterns and somatic indicators.\n• Structured continuity points for the upcoming 1:1 session.\n\n**3. Recommended Practice Integration:**\n• You can incorporate these items directly into your client's SOAP documentation or assign as follow-up reflection.\n\nWould you like me to format these notes into a complete SOAP record or draft a client homework prompt based on this image?`
      } else if (lower.includes("soap") || lower.includes("note") || lower.includes("summary") || lower.includes("case")) {
        reply = `Here is your clinical session synthesis structured by your practice assistant for documentation excellence:\n\n### 📋 Clinical Encounter & Thematic Formulation\n\n**1. Subjective & Affective Presentation:**\nClient arrived presenting situational anxiety and psychomotor restlessness related to interpersonal conflict and workload boundary erosion. Affect was congruent with reported distress; insight demonstrated high readiness for change.\n\n**2. Somatic & Psychological Formulations:**\n• Primary Vagal State: Sympathetic activation with chronic hypervigilance around perceived expectations.\n• Key Cognitive Schema: 'If I do not absorb everyone's demands, I am inherently unsafe / unvalued.'\n\n**3. Interventions Applied & Therapeutic Modalities:**\n• Somatic Experiencing: Guided interoceptive tracking of chest constriction, facilitating a restorative physiological sigh.\n• ACT Defusion: Separated identity from the perceived urgency of external demands.\n\n**4. Clinical Treatment Plan & Continuity:**\n• Client assigned 1 daily evening self-compassion check-in in the OpenHand journal.\n• Next 1:1 session scheduled for 7 days to evaluate boundary enforcement in high-friction environments.`
      } else if (lower.includes("prompt") || lower.includes("homework") || lower.includes("reflection")) {
        reply = `Here are 4 high-impact reflection prompts prepared by your practice assistant to assign to your client:\n\n1. *"Notice the exact moment this week where you felt an impulse to apologize for simply existing or having a need. What felt dangerous about taking up space?"*\n2. *"When your body felt tense or contracted recently, what boundary was being quietly compromised?"*\n3. *"What is an unwritten rule you learned in childhood about what you must do to earn love or approval that you are ready to retire?"*\n4. *"Imagine your wisest, most compassionate future self standing behind you right now with a hand on your shoulder. What permission are they giving you?"*\n\n💡 *Assistant Note: These prompts work exceptionally well when assigned right after a high-emotion 1:1 session while the insight is still fresh.*`
      } else if (lower.includes("burnout") || lower.includes("countertransference") || lower.includes("fatigue") || lower.includes("holding space")) {
        reply = `Colleague, as your practice assistant, I want to gently check in on your own wellbeing. Holding space for deep human pain is profound work, but it takes an invisible somatic toll on your own nervous system.\n\n**A Practice Assistant Check-In for You:**\n• Where are you absorbing your clients' urgency as your own?\n• Are you working harder than the client during the session? (A classic marker of over-functioning empathy).\n• Have you cleared your somatic palate between sessions, or are you carrying client energy into your evening?\n\nTake a deep, deliberate exhale. Ground your pelvis and feet into the earth. You are the instrument through which healing occurs — keep your instrument tuned and rested.`
      } else {
        reply = `Greetings. As your dedicated Practice Assistant, I am ready to support your daily clinical and administrative workflow:\n\n• **SOAP & Session Synthesis:** Converting raw session debriefs into pristine, auditable clinical notes.\n• **Client Reflection Prompts:** Generating tailored therapeutic questions and journaling exercises for your clients.\n• **Case Structuring & Modalities:** Conceptualizing cases with ACT, Somatic Experiencing, IFS, and CBT frameworks.\n• **Image & Artifact Processing:** Upload handwritten notes or whiteboard sketches for instant transcription.\n• **Practitioner Sustainability:** Managing capacity, preventing burnout, and supporting your professional practice.\n\nWhat would you like assistance with today?`
      }
    }

    return res.status(200).json({
      success: true,
      reply,
      practicalExercise,
      role,
      source: "master_engine",
    })
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: "AURA engine encountered an issue.",
      error: error.message,
    })
  }
}


