const SessionNoteDraft = require("../models/SessionNoteDraft")
const ConsentLog = require("../models/ConsentLog")

exports.generateDraftNotes = async (req, res) => {
  try {
    const { bookingId, clientId, rawTranscript } = req.body
    const practitionerId = req.user.id

    // Hard Rule 1: Check active consent before running
    const activeConsent = await ConsentLog.findOne({
      client: clientId,
      isActive: true,
      consentType: { $in: ["copilot_notes", "copilot_audio", "aura_notes", "aura_audio"] },
    })

    if (!activeConsent) {
      return res.status(403).json({
        success: false,
        message: "Consent required: The client has not granted active consent for AI AURA processing.",
        hardRule: "Nothing records or processes without live revocable consent.",
      })
    }

    // Build draft notes from rawTranscript (practitioner-submitted session notes)
    // AURA processes whatever the practitioner provides — no fake pre-written content
    let draftNotes
    let suggestedPrompts

    if (rawTranscript && rawTranscript.trim().length > 20) {
      // Process the submitted transcript into structured session notes
      const lines = rawTranscript.trim().split(/[\n.]+/).filter(Boolean)
      const keyThemes = lines.slice(0, 3).join(". ")

      draftNotes = `Practitioner Summary:\n${keyThemes}\n\nNote: This draft was generated from your session transcript. Review and edit before saving to client record.`

      // Extract potential reflection themes from transcript keywords
      const lowerTranscript = rawTranscript.toLowerCase()
      const themes = []
      if (lowerTranscript.includes("anxi") || lowerTranscript.includes("stress") || lowerTranscript.includes("worry")) {
        themes.push("What would it feel like to let one worry go without resolving it first?")
      }
      if (lowerTranscript.includes("boundar") || lowerTranscript.includes("limit")) {
        themes.push("Notice one boundary you protected this week, however small.")
      }
      if (lowerTranscript.includes("relationship") || lowerTranscript.includes("connect") || lowerTranscript.includes("family")) {
        themes.push("What do you need from your relationships right now that you haven't asked for?")
      }
      if (themes.length === 0) {
        themes.push("What felt heavy this week that you carried without asking for support?")
      }
      suggestedPrompts = themes.slice(0, 2)
    } else {
      // No transcript provided — create an empty structured skeleton
      draftNotes = `Practitioner Summary:\n[Add your session summary here]\n\nTechnique Used: [Add technique]\nKey Insight: [Add key insight or breakthrough]\n\nNote: No transcript was submitted. Please fill in session notes manually.`
      suggestedPrompts = [
        "What felt heavy this week that you carried without asking for support?",
        "Notice one moment in the last 3 days where you reacted differently than you would have 6 months ago.",
      ]
    }

    const draft = await SessionNoteDraft.create({
      booking: bookingId,
      practitioner: practitionerId,
      client: clientId,
      rawTranscript: rawTranscript || "",
      draftNotes,
      suggestedReflectionPrompts: suggestedPrompts,
      status: "draft",
    })

    return res.status(200).json({
      success: true,
      message: "Draft notes generated by AURA. Practitioner approval required before saving.",
      draft,
      hardRules: [
        "Never messages the client directly",
        "Never diagnoses or suggests medication",
        "Requires explicit practitioner approval before saving to client record",
      ],
    })
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: "Failed to generate AURA draft notes",
      error: error.message,
    })
  }
}

exports.approveDraftNotes = async (req, res) => {
  try {
    const { draftId, editedNotes } = req.body
    const practitionerId = req.user.id

    const draft = await SessionNoteDraft.findOne({ _id: draftId, practitioner: practitionerId })
    if (!draft) {
      return res.status(404).json({
        success: false,
        message: "Draft notes not found or unauthorized",
      })
    }

    draft.draftNotes = editedNotes || draft.draftNotes
    draft.status = "approved"
    draft.approvedAt = new Date()
    await draft.save()

    return res.status(200).json({
      success: true,
      message: "Session notes approved and committed to client record.",
      draft,
    })
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: "Failed to approve draft notes",
      error: error.message,
    })
  }
}
