const SessionNoteDraft = require("../models/SessionNoteDraft")
const ConsentLog = require("../models/ConsentLog")

exports.generateDraftNotes = async (req, res) => {
  try {
    const { bookingId, clientId, rawTranscript } = req.body
    const practitionerId = req.user.id

    // Hard Rule 1: Check active consent before running
    const activeConsent = await ConsentLog.findOne({
      client: clientId,
      isActive: true,
      consentType: { $in: ["copilot_notes", "copilot_audio", "aura_notes", "aura_audio"] },
    })

    if (!activeConsent) {
      return res.status(403).json({
        success: false,
        message: "Consent required: The client has not granted active consent for AI AURA processing.",
        hardRule: "Nothing records or processes without live revocable consent.",
      })
    }

    // Mock/AURA integration draft note generation
    const mockDraftNotes = `Practitioner Summary:\nClient explored themes of high-functioning anxiety surrounding recent workplace transitions. Expressed reluctance to request assistance until burnout symptoms manifested.\n\nTechnique Used: Cognitive Reframing & Grounding\nKey Insight: Breakthrough moment regarding boundaries around availability.`

    const mockPrompts = [
      "What felt heavy this week that you carried without asking for support?",
      "Notice one boundary you set today that protected your energy.",
    ]

    const draft = await SessionNoteDraft.create({
      booking: bookingId,
      practitioner: practitionerId,
      client: clientId,
      rawTranscript: rawTranscript || "",
      draftNotes: mockDraftNotes,
      suggestedReflectionPrompts: mockPrompts,
      status: "draft",
    })

    return res.status(200).json({
      success: true,
      message: "Draft notes generated by AURA. Practitioner approval required before saving.",
      draft,
      hardRules: [
        "Never messages the client directly",
        "Never diagnoses or suggests medication",
        "Requires explicit practitioner approval before saving to client record",
      ],
    })
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: "Failed to generate AURA draft notes",
      error: error.message,
    })
  }
}

exports.approveDraftNotes = async (req, res) => {
  try {
    const { draftId, editedNotes } = req.body
    const practitionerId = req.user.id

    const draft = await SessionNoteDraft.findOne({ _id: draftId, practitioner: practitionerId })
    if (!draft) {
      return res.status(404).json({
        success: false,
        message: "Draft notes not found or unauthorized",
      })
    }

    draft.draftNotes = editedNotes || draft.draftNotes
    draft.status = "approved"
    draft.approvedAt = new Date()
    await draft.save()

    return res.status(200).json({
      success: true,
      message: "Session notes approved and committed to client record.",
      draft,
    })
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: "Failed to approve draft notes",
      error: error.message,
    })
  }
}
